server:
  port: 8080
  servlet:
    context-path: /bootcamp
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://uuyoqoikbpmamu:91f1c572acc5868c3fa4f3e7a0d9ee6e065ac962c394d285168e9682ed667e5c@ec2-34-193-112-164.compute-1.amazonaws.com:5432/d7jkb9rdre1rql
    username: uuyoqoikbpmamu
    password: 91f1c572acc5868c3fa4f3e7a0d9ee6e065ac962c394d285168e9682ed667e5c
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  
